version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DIOSkira103*
      POSTGRES_DB: localdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  api:
    build:
      context: .
      dockerfile: ReviewAnythingAPI/Dockerfile
    depends_on:
      - db
    env_file:
      - ./ReviewAnythingAPI/config/development.env
    ports:
      - "5000:80"
    
  blazor:
    build:
      context: .
      dockerfile: BlazorApp1/Dockerfile
      target: develop
    depends_on:
      - api
    env_file:
      - ./BlazorApp1/config/development.env
    ports:
      - "5002:80"
    environment:
      Api__BaseUrl: "http://api"
      ASPNETCORE_URLS: "http://0.0.0.0:80"
    volumes:
      - ./BlazorApp1:/src/BlazorApp1
      - ~/.nuget:/root/.nuget
      - /src/BlazorApp1/bin
      - /src/BlazorApp1/obj
        
volumes:
  pgdata: